import { Profile } from "incyclist-ant-plus"
import { LegacyProfile } from "./types"

const brands = [
    'Garmin,1',
    'garmin_fr405_antfs,2',
    'Zephyr,3',
    'Dayton,4',
    'idt,5',
    'SRM,6',
    'Quarq,7',
    'ibike,8',
    'Saris,9',
    'spark_hk,10',
    'Tanita,11',
    'echowell,12',
    'Dynastream_oem,13',
    'Nautilus,14',
    'Dynastream,15',
    'Timex,16',
    'Metrigear,17',
    'Xelic,18',
    'Beurer,19',
    'Cardiosport,20',
    'A&D,21',
    'Hmm,22',
    'Suunto,23',
    'Thita Elektronik,24',
    'Gpulse,25',
    'Clean Mobile,26',
    'Pedal Brain,27',
    'Peaksware,28',
    'Saxonar,29',
    'Lemond Fitness,30',
    'Dexcom,31',
    'Wahoo,32',
    'Octane,33',
    'Archinoetics,34',
    'The Hurt Box,35',
    'Citizen Systems,36',
    'Magellan,37',
    'Osynce,38',
    'Holux,39',
    'Concept2,40',
    'One Giant Leap,42',
    'Ace Sensor,43',
    'Brim Brothers,44',
    'Xplova,45',
    'Perception Digital,46',
    'Bf1systems,47',
    'Pioneer,48',
    'Spantec,49',
    'Metalogics,50',
    '4iiiis,51',
    'Seiko,52',
    'Seiko,53',
    'Ifor Powell,54',
    'Maxwell Guider,55',
    'Star rac,56',
    'Breakaway,57',
    'Alatech,58',
    'Mio,59',
    'Rotor,60',
    'Geonaute,61',
    'Id Bike,62',
    'Specialized,63',
    'Wtek,64',
    'Physical Enterprises,65',
    'North Pole,66',
    'Bkool,67',
    'Cateye,68',
    'Stages,69',
    'Sigma,70',
    'Tomtom,71',
    'Peripedal,72',
    'Wattbike,73',
    'Moxy,76',
    'Ciclosport,77',
    'Powerbahn,78',
    'Acorn,79',
    'Lifebeam,80',
    'Bontrager,81',
    'Wellgo,82',
    'Scosche,83',
    'Magura,84',
    'Woodway,85',
    'Elite,86',
    'Nielsen Kellerman,87',
    'DK City,88',
    'Tacx,89',
    'Direction,90',
    'Magtonic,91',
    '1partcarbon,92',
    'Inside Ride,93',
    'Sound Of Motion,94',
    'Stryd,95',
    'icg,96',
    'MiPulse,97',
    'Bsx Athletics,98',
    'Look,99',
    'Campagnolo,100',
    'Body Bike Smart,101',
    'Praxisworks,102',
    'Limits,103',
    'Topaction,104',
    'Cosinuss,105',
    'Fitcare,106',
    'Magene,107',
    'Giant,108',
    'Tigrasport,109',
    'Salutron,110',
    'Technogym,111',
    'Bryton,112',
    'Latitude,113',
    'Soaring,114',
    'Igpsport,115',
    'Thinkrider,116',
    'Gopher,117',
    'Waterrower,118',
    'Orangetheory,119',
    'Inpeak,120',
    'Kinetic,121',
    'Johnson,122',
    'Polar,123',
    'Seesense,124',
    'NCI,125',
    'Development,255',
    'Healthandlife,257',
    'Lezyne,258',
    'Scribe,259',
    'Zwift,260',
    'Watteam,261',
    'Recon,262',
    'Favero,263',
    'Dynovelo,264',
    'Strava,265',
    'Precor,266',
    'Bryton,267',
    'Sram,268',
    'Navman,269',
    'Cobi,270',
    'Spivi,271',
    'Mio Magellan,272',
    'Evesports,273',
    'Sensitivus Gauge,274',
    'Podoon,275',
    'Life Time Fitness,276',
    'Falco,277',
    'Minoura,278',
    'Cycliq,279',
    'Luxottica,280',
    'Trainer Road,281',
    'The Sufferfest,282',
    'Fullspeedahead,283',
    'Virtualtraining,284',
    'Feedbacksports,285',
    'Omata,286',
    'VDO,287',
    'Magneticdays,288',
    'Hammerhead,289',
    'Kinetic By Kurt,290',
    'Shapelog,291',
    'Dabuziduo,292',
    'Jetblack,293',
    'Coros,294',
    'Virtugo,295',
    'Velosense,296',
    'Cycligentinc,297',
    'Actigraphcorp,5759'
]

const brandLookup = brands.map( str => {
    const [name,id] = str.split(',')
    return {name,id:Number(id)}
})


export const getBrand = (manId:number) => {
    const found = brandLookup.find( l => l.id===manId)
    if (found)
        return found.name
    return;
}

export const mapLegacyProfile = ( legacy:LegacyProfile ):Profile => {
    switch (legacy){
        case 'Heartrate Monitor': return 'HR'
        case 'Power Meter': return 'PWR'
        case 'Smart Trainer': return 'FE'
        case 'Cadence Sensor':return 'CAD'
        case 'Speed Sensor': return 'SPD'
        case 'Speed + Cadence Sensor': return 'SC'
    }
} 

