import { EventLogger } from 'gd-eventlog';
import CyclingMode from '../CyclingMode';
import DeviceAdapterBase, { DeviceAdapter } from '../Device';
interface DaumAdapter {
    getCurrentBikeData(): Promise<any>;
}
export default class DaumAdapterBase extends DeviceAdapterBase implements DeviceAdapter, DaumAdapter {
    bike: any;
    ignoreHrm: boolean;
    ignoreBike: boolean;
    ignorePower: boolean;
    distanceInternal: number;
    paused: boolean;
    stopped: boolean;
    data: any;
    currentRequest: any;
    requests: Array<any>;
    iv: any;
    logger: EventLogger;
    cyclingMode: CyclingMode;
    userSettings: any;
    bikeSettings: any;
    constructor(props: any, bike: any);
    setCyclingMode(mode: CyclingMode): void;
    getSupportedCyclingModes(): Array<any>;
    getCyclingMode(): CyclingMode;
    getDefaultCyclingMode(): CyclingMode;
    setUserSettings(userSettings: any): void;
    setBikeSettings(bikeSettings: any): void;
    getWeight(): any;
    getCurrentBikeData(): Promise<any>;
    getBike(): any;
    isBike(): boolean;
    isPower(): boolean;
    isHrm(): boolean;
    setIgnoreHrm(ignore: any): void;
    setIgnoreBike(ignore: any): void;
    isStopped(): boolean;
    initData(): void;
    start(props?: any): Promise<any>;
    startUpdatePull(): void;
    connect(): void;
    close(): any;
    logEvent(event: any): void;
    stop(): Promise<boolean>;
    pause(): Promise<boolean>;
    resume(): Promise<boolean>;
    sendUpdate(data: any): Promise<void>;
    update(): Promise<void>;
    updateData(data: any, bikeData: any): any;
    transformData(bikeData: any): any;
    sendRequest(request: any): Promise<any>;
    sendBikeUpdate(request: any): Promise<unknown>;
}
export {};
