export declare function bin2esc(arr: any): any[];
export declare function esc2bin(arr: any): any[];
export declare function checkSum(cmdArr: any, payload: any): string;
export declare function buildMessage(command: any, payload?: any): any[];
export declare function getMessageData(command: any): any[];
export declare function hexstr(arr: any, start?: any, len?: any): string;
export declare function getHex(i: any): string;
export declare function append(cmd: any, arr: any): void;
export declare function ascii(c: any): any;
export declare function charArrayToString(arr: any): string;
export declare function asciiArrayToString(arr: any): string;
export declare function getAsciiArrayFromStr(str: any): any[];
export declare function Float32ToHex(float32: any): any;
export declare function Float32ToIntArray(float32: any): any[];
export declare function Int16ToIntArray(int16: any): any[];
export declare function Int32ToIntArray(int32: any): any[];
export declare function getReservedCommandKey(cmdStr: any): any;
export declare function parseTrainingData(payload: any): {
    time: number;
    heartrate: number;
    speed: number;
    slope: number;
    distance: number;
    cadence: number;
    power: number;
    physEnergy: number;
    realEnergy: number;
    torque: number;
    gear: number;
    deviceState: number;
    speedStatus: string;
};
