name: Release

on:
  push: 
    tags:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3

    - name: test 
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: echo "Setting up a new release"
      
