name: Release

on:
  push: 
    tags:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - run: echo "Creating a new Release ..."

      
